# Generated by Django 4.1.7 on 2023-04-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_updated_at_profilephoto_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='image',
            field=models.ImageField(upload_to='chat/images'),
        ),
    ]
