# Generated by Django 4.2 on 2023-04-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_profilephoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_photo_removed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='chat.profile'),
        ),
    ]
