# Generated by Django 4.2 on 2023-07-24 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_privatechat_privatechatparticipant_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='participant_users',
            field=models.ManyToManyField(related_name='private_chats', through='chat.PrivateChatParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_chat_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
