# Generated by Django 4.2 on 2023-07-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_privatechat_participant_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='termination_date',
            new_name='terminated_at',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='last_active',
        ),
    ]
