# Generated by Django 4.2 on 2023-08-03 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_groupchat_alter_privatechatparticipant_user_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='is_photo_removed',
        # ),
        migrations.AlterField(
            model_name='groupchatadmin',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='chat.profile'),
        ),
    ]
