# Generated by Django 4.2 on 2023-08-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_profile_is_photo_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='participant_users_tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
