# Generated by Django 4.2 on 2023-08-15 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('chat', '0012_privatechat_participant_users_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.PositiveIntegerField()),
                ('parent_chat_type', models.CharField(choices=[('PC', 'PRIVATE CHAT'), ('GC', 'GROUP CHAT')], max_length=2)),
                ('content_format', models.CharField(choices=[('TXT', 'TEXT'), ('IMG', 'IMAGE'), ('AUD', 'AUDIO'), ('VID', 'VIDEO')], max_length=3)),
                ('time_tag', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('delivery_status', models.CharField(choices=[('P', 'IN_PROGRESS'), ('S', 'SENT'), ('D', 'DELIVERED'), ('V', 'VIEWED')], default='P', max_length=1)),
                ('parent_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='chat.message')),
            ],
        ),
    ]
