# Generated by Django 4.2.4 on 2024-10-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_rename_time_tag_message_time_stamp_chatclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatClient',
        ),
    ]
